improve sync package db handling
ashos/ashos pull request #45
Opened 2022-08-13 23:15 UTC by CuBeRJAN

previously if two snapshots had a different version of the same package a sync would lead to a duplicate database entry
this should no longer be the case

2022-08-13 23:16 UTC, CuBeRJAN commented
everything should work fine, but we have to make sure it's 100% as this could cause issues otherwise

2022-08-13 23:34 UTC, CuBeRJAN commented
now that issue should be out of the way, all that's left to do is test this

2022-08-13 23:44 UTC, CuBeRJAN commented
I've done some testing, everything seems to be well! I'll leave this PR open for now and if now issues show up we can merge!

2022-08-14 12:18 UTC, i2 commented
I'd like this PR to stay open for a few weeks.

2022-08-15 13:46 UTC, CuBeRJAN commented
I'm pulling changes from main into this repository since I use it for testing. All seems good so far!

2022-08-17 15:05 UTC, CuBeRJAN commented
I've pushed another change into this branch, this one makes it so that 'ast sync' now syncs live, I've tested it plenty so it should be good. There's a new '--not-live' flag for sync. At this point this branch is a complete rework of the sync operation.

2022-09-08 23:10 UTC, i2 requested changes
Same thing applies to this PR:
1. **Important: I skimmed through the code and I think there are parts of it that can be abstracted away and put in ashpk_core.py**. We want to keep distro-specific ashpk.py files as small as possible (for easier translation to other distros)
2. Rest of the modifications should be manually merged to ./src/distros/arch/ashpk.py

2022-09-15 17:20 UTC, i2 commented
Things look good and it's time to close this PR as well! I have included it in #69.

2022-09-15 17:20 UTC, closed without merging